# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js image as the base image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm install

# Copy the entire source code into the image
COPY . .

# Build the TypeScript code
RUN npm run build

# Build the WASM code
RUN npm run asbuild

# Use a lightweight server to serve static files
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy the build artifacts from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/index.html /app/index.html
COPY --from=builder /app/node_modules /app/node_modules

# Install a simple static file server
RUN npm install -g serve

# Expose port 3000
EXPOSE 3000

# Command to run the application
CMD ["serve", "-s", "dist", "-l", "3000"]
